"""empty message

Revision ID: 0887a409268e
Revises: 13281afdc832
Create Date: 2024-09-05 18:15:12.158718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0887a409268e'
down_revision = '13281afdc832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('todo_name', sa.String(), nullable=True),
    sa.Column('move_1', sa.String(), nullable=True),
    sa.Column('move_2', sa.String(), nullable=True),
    sa.Column('move_3', sa.String(), nullable=True),
    sa.Column('move_4', sa.String(), nullable=True),
    sa.Column('move_pt_1', sa.Integer(), nullable=True),
    sa.Column('move_pt_2', sa.Integer(), nullable=True),
    sa.Column('move_pt_3', sa.Integer(), nullable=True),
    sa.Column('move_pt_4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_todos')
    # ### end Alembic commands ###
