"""empty message

Revision ID: 23dac3a473ee
Revises: 
Create Date: 2024-09-10 19:28:39.051668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dac3a473ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('user_path', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('user_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('todo_name', sa.String(), nullable=True),
    sa.Column('todo_pt', sa.Integer(), nullable=True),
    sa.Column('todo_pt_result', sa.Integer(), nullable=True),
    sa.Column('move_1', sa.String(), nullable=True),
    sa.Column('move_2', sa.String(), nullable=True),
    sa.Column('move_3', sa.String(), nullable=True),
    sa.Column('move_4', sa.String(), nullable=True),
    sa.Column('move_pt_1', sa.Integer(), nullable=True),
    sa.Column('move_pt_2', sa.Integer(), nullable=True),
    sa.Column('move_pt_3', sa.Integer(), nullable=True),
    sa.Column('move_pt_4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_todos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
