"""empty message

Revision ID: 66575f8f409e
Revises: 0887a409268e
Create Date: 2024-09-05 22:21:43.752605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66575f8f409e'
down_revision = '0887a409268e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo_pt', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.drop_column('todo_pt')

    # ### end Alembic commands ###
