"""empty message

Revision ID: 86f7692786ea
Revises: 45023e687c84
Create Date: 2024-10-11 12:10:24.172576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f7692786ea'
down_revision = '45023e687c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_day', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.drop_column('target_day')

    # ### end Alembic commands ###
