"""empty message

Revision ID: cb8387e0859d
Revises: 86f7692786ea
Create Date: 2024-11-07 15:45:48.276201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8387e0859d'
down_revision = '86f7692786ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.drop_column('reward')

    # ### end Alembic commands ###
