"""empty message

Revision ID: e454d9b13008
Revises: 66575f8f409e
Create Date: 2024-09-06 18:21:32.603133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e454d9b13008'
down_revision = '66575f8f409e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('todo_pt_result', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_todos', schema=None) as batch_op:
        batch_op.drop_column('todo_pt_result')

    # ### end Alembic commands ###
